export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const UPDATE_TIME_RANGE = 'UPDATE_TIME_RANGE';

export const LOAD_USER_TOP_SUCCESS = 'LOAD_USER_TOP_SUCCESS';

// Playlists
export const LOAD_CREATED_PLAYLISTS_SUCCESS = 'LOAD_CREATED_PLAYLISTS_SUCCESS';
export const LOAD_CREATED_PLAYLISTS_FAILURE = 'LOAD_CREATED_PLAYLISTS_FAILURE';
